name: Release
on:
  push:
    branches:
      - master
      - release/**
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please-action.outputs.release_created }}
      tag_name: ${{ steps.release-please-action.outputs.tag_name }}
      major: ${{ steps.release-please-action.outputs.major }}
      minor: ${{ steps.release-please-action.outputs.minor }}
    steps:
      - uses: actions/checkout@v4
      - name: Release please
        id: release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple

  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Upload documents to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            README.md
          tag_name: ${{ needs.release-please.outputs.tag_name }}
