name: Tests
on:
  push:
  workflow_dispatch:  # Now you can manually trigger this workflow from the Actions tab!

jobs:
  build-temp-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: build-temp-container
        run: |
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          docker build -t mentalmonkeysoftware/app-token:temp -f prebuild.Dockerfile .
          docker push mentalmonkeysoftware/app-token:temp
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  test-container:
    needs: [build-temp-container]
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/checkout@master
      
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v1
    #   env:
    #     INPUT_APP_PEM: ${{ secrets.APP_PEM }}
    #     INPUT_APP_ID: ${{ secrets.APP_ID }}

    # tested with https://github.com/apps/fastpages-chatops
    # - name: test
    #   id: test
    #   uses: docker://mentalmonkeysoftware/app-token:temp
    #   env:
    #     INPUT_APP_PEM: ${{ secrets.APP_PEM }}
    #     INPUT_APP_ID: ${{ secrets.APP_ID }}

    - name: pre-build action image
      run: |
        cd $GITHUB_WORKSPACE
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker build -t mentalmonkeysoftware/app-token -f prebuild.Dockerfile .
        docker push mentalmonkeysoftware/app-token 
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    #    # tested withhttps://github.com/apps/fastpages-chatops
    # - name: final-test
    #   uses: mentalmonkeysoftware/actions-app-token@master
    #   with:
    #     APP_PEM: ${{ secrets.APP_PEM }}
    #     APP_ID: ${{ secrets.APP_ID }}
